apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: km-app
  namespace: argocd
spec:
  project: project1
  destination:
    namespace: ns-2
    server: "https://kubernetes.default.svc"
  source:
    path: manifest
    repoURL: "https://github.com/anuj-teotia/argo-km.git"
    targetRevision: HEAD
