apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project1
  namespace: argocd
spec:
  description: Basic Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: 'ns-1'
    server: '*'

