apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: km-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: guestbook
    server: "https://kubernetes.default.svc"
  source:
    path: km-app-manifests
    repoURL: "https://github.com/anuj-teotia/argo-km.git"
    targetRevision: HEAD