apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: km-app-heml
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    path: helm
    repoURL: "https://github.com/anuj-teotia/argo-km.git"
    targetRevision: HEAD
    helm:
      values: |
        name: helm-km-app
        version: app-v1
