apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auto-sync
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    path: manifest
    repoURL: "https://github.com/anuj-teotia/argo-km.git"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true





### Now try to manually  scale replicas and it should revert the change
### kubectl scale deployment/argo-km --replicas 3
