apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-km
  labels:
    app: argo-km
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-km
  template:
    metadata:
      labels:
        app: argo-km
    spec:
      containers:
      - name: argo-km
        image: docker.io/anujteotialive/argo-km:app-v1
        ports:
        - containerPort: 80
