apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-phases
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    path: manifest-sync-phases
    repoURL: "https://github.com/anuj-teotia/argo-km.git"
    targetRevision: HEAD
  syncPolicy:
    automated: {} 
